// ============================================================================
//  SEND EMAIL
//  Generates the report ZIP and optionally sends it via Gmail.
//
//  Required .env variables:
//    EMAIL_USER=your.gmail@gmail.com
//    EMAIL_PASS=your-app-password       ← Gmail App Password (not account password)
//    EMAIL_TO=recipient@example.com     ← comma-separated for multiple recipients
//    AUTO_SEND_EMAIL=true               ← set true to auto-send after every run
//    PROJECT_NAME=Teambase-BenefitNet   ← optional, defaults to package.json name
//
//  Gmail App Password setup:
//    1. Go to https://myaccount.google.com/security
//    2. Enable 2-Step Verification
//    3. Go to App Passwords → create one for "Mail"
//    4. Paste the 16-char password as EMAIL_PASS in .env
// ============================================================================

require("dotenv").config({ path: require("path").join(__dirname, "../.env") });

const path = require("path");
const nodemailer = require("nodemailer");
const { generateReport } = require(path.join(__dirname, "./generate-report"));

// ── Helpers ──────────────────────────────────────────────────────────────────

function getProjectName() {
  if (process.env.PROJECT_NAME) return process.env.PROJECT_NAME;
  try {
    return require(path.join(__dirname, "../package.json")).name || "qa-project";
  } catch {
    return "qa-project";
  }
}

function getReadableTimestamp() {
  return new Date().toLocaleString("en-IN", {
    timeZone: "Asia/Kolkata",
    dateStyle: "full",
    timeStyle: "medium",
  });
}

// ── Email HTML template ───────────────────────────────────────────────────────

function buildEmailBody(projectName, zipFileName, timestamp) {
  return `
<div style="font-family: Arial, sans-serif; max-width: 620px; margin: auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">

  <!-- Header -->
  <div style="background: #1a1a2e; color: #fff; padding: 20px 24px;">
    <h2 style="margin: 0; font-size: 18px;">🎭 Playwright Execution Report</h2>
    <p style="margin: 6px 0 0; font-size: 13px; opacity: 0.7;">QA Automation Framework — TeamBase BenefitNet</p>
  </div>

  <!-- Body -->
  <div style="padding: 24px;">
    <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
      <tr>
        <td style="padding: 8px 0; color: #555; width: 150px;"><strong>Project</strong></td>
        <td style="padding: 8px 0;">${projectName}</td>
      </tr>
      <tr>
        <td style="padding: 8px 0; color: #555;"><strong>Executed At</strong></td>
        <td style="padding: 8px 0;">${timestamp} IST</td>
      </tr>
      <tr>
        <td style="padding: 8px 0; color: #555;"><strong>Report File</strong></td>
        <td style="padding: 8px 0;">
          <code style="background:#f4f4f4; padding:2px 6px; border-radius:4px; font-size:12px;">${zipFileName}</code>
        </td>
      </tr>
    </table>

    <hr style="border:none; border-top:1px solid #eee; margin:20px 0;" />

    <p style="font-size: 14px; color: #333; line-height: 1.6;">
      The <strong>Playwright HTML Report</strong> is attached as a ZIP file.<br/>
      Extract the ZIP and open <code style="background:#f4f4f4; padding:1px 5px; border-radius:3px;">playwright-report/index.html</code>
      in any browser to view full test results, screenshots, videos, and traces.
    </p>

    <div style="background: #f8f9fa; border-left: 4px solid #1a1a2e; padding: 12px 16px; border-radius: 0 4px 4px 0; margin-top: 16px;">
      <p style="margin: 0; font-size: 13px; color: #555;">
        <strong>Contents of ZIP:</strong><br/>
        📁 <code>playwright-report/</code> — HTML report (open index.html)<br/>
        📁 <code>test-results/</code> — screenshots, videos, traces<br/>
        📁 <code>logs/</code> — IST-timestamped plain text log files
      </p>
    </div>

    <p style="font-size: 11px; color: #aaa; margin-top: 24px; border-top: 1px solid #eee; padding-top: 12px;">
      Auto-generated by QA Automation Framework. Do not reply to this email.
    </p>
  </div>
</div>`;
}

// ── Main function ─────────────────────────────────────────────────────────────

/**
 * Generate ZIP and optionally send email.
 * @param {boolean} sendNow  true = send email, false = ZIP only
 */
async function sendEmail(sendNow = true) {
  const projectName = getProjectName();

  // ── Step 1: Always generate the ZIP ─────────────────────────────────────
  // console.log(`\n  Generating report ZIP for: ${projectName}`);
  const { zipFileName, zipPath } = await generateReport(projectName);

  // ── Step 2: Skip email if not requested ──────────────────────────────────
  if (!sendNow) {
    // console.log(`  Email Mode    : MANUAL`);
    // console.log(`  To send now   : node reports/send-email.js`);
    return;
  }

  // ── Step 3: Validate .env credentials ───────────────────────────────────
  const { EMAIL_USER, EMAIL_PASS, EMAIL_TO } = process.env;

  if (!EMAIL_USER || !EMAIL_PASS || !EMAIL_TO) {
    const missing = [
      !EMAIL_USER ? "EMAIL_USER" : null,
      !EMAIL_PASS ? "EMAIL_PASS" : null,
      !EMAIL_TO ? "EMAIL_TO" : null,
    ].filter(Boolean).join(", ");

    throw new Error(
      `Missing .env variables: ${missing}\n` +
      `Add them to your .env file at the project root:\n` +
      `  EMAIL_USER=your.gmail@gmail.com\n` +
      `  EMAIL_PASS=your-16-char-app-password\n` +
      `  EMAIL_TO=recipient@example.com`
    );
  }

  // ── Step 4: Send via Gmail SMTP ──────────────────────────────────────────
  const timestamp = getReadableTimestamp();
  const subject = `[QA Report] ${projectName} — Playwright Execution Report`;
  const htmlBody = buildEmailBody(projectName, zipFileName, timestamp);
  const recipients = EMAIL_TO.split(",").map(e => e.trim()).filter(Boolean);

  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: EMAIL_USER,
      pass: EMAIL_PASS,
    },
  });

  await transporter.sendMail({
    from: `"QA Automation" <${EMAIL_USER}>`,
    to: recipients.join(", "),
    subject,
    html: htmlBody,
    attachments: [{ filename: zipFileName, path: zipPath }],
  });

  // console.log(`  Email Sent    : ${recipients.join(", ")}`);
  // console.log(`  Subject       : ${subject}`);
}

module.exports = sendEmail;

// Allow direct execution: node reports/send-email.js
if (require.main === module) {
  sendEmail(true)
    .then(() => { }) // console.log("\n  Done.\n")
    .catch(err => {
      console.error("\n[send-email] Error:", err.message || err);
      process.exit(1);
    });
}